[package]
name = "link-ext"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain="0.12.3"
reqwest="0.11.21"
tokio = {version = "1.35.1", features = ["full"] }
select = "0.6.0"
